export default [
   {
      id: 1,
      name: "GOR Adz-Zikra",
      image: "basket.jpg",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut rem aut in consectetur amet perferendis, quaerat labore voluptatem voluptas culpa, dolorem officiis, iusto temporibus vitae eos totam laboriosam velit necessitatibus.",
      price: 25000,
      location: "Jalan Madura",
      city: "Depok",
      rating: "4.70",
   },
   {
      id: 2,
      name: "GOR Al-Hidayah",
      image: "badminton.jpg",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut rem aut in consectetur amet perferendis, quaerat labore voluptatem voluptas culpa, dolorem officiis, iusto temporibus vitae eos totam laboriosam velit necessitatibus. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut rem aut in consectetur amet perferendis, quaerat labore voluptatem voluptas culpa, dolorem officiis, iusto temporibus vitae eos totam laboriosam velit necessitatibus.",
      price: 30000,
      location: "Jalan Enggano",
      city: "Mataram",
      rating: "4.99",
   },
   {
      id: 3,
      name: "GOR Ar-Rahmah",
      image: "sepak-bola.jpg",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut rem aut in consectetur amet perferendis, quaerat labore voluptatem voluptas culpa, dolorem officiis, iusto temporibus vitae eos totam laboriosam velit necessitatibus.",
      price: 30000,
      location: "Jalan Bali",
      city: "Palembang",
      rating: "4.39",
   },
   {
      id: 4,
      name: "GOR Adz-Zikra",
      image: "basket.jpg",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut rem aut in consectetur amet perferendis, quaerat labore voluptatem voluptas culpa, dolorem officiis, iusto temporibus vitae eos totam laboriosam velit necessitatibus.",
      price: 25000,
      location: "Jalan Madura",
      city: "Depok",
      rating: "4.70",
   },
   {
      id: 5,
      name: "GOR Al-Hidayah",
      image: "badminton.jpg",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut rem aut in consectetur amet perferendis, quaerat labore voluptatem voluptas culpa, dolorem officiis, iusto temporibus vitae eos totam laboriosam velit necessitatibus. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut rem aut in consectetur amet perferendis, quaerat labore voluptatem voluptas culpa, dolorem officiis, iusto temporibus vitae eos totam laboriosam velit necessitatibus.",
      price: 30000,
      location: "Jalan Enggano",
      city: "Mataram",
      rating: "4.99",
   },
   {
      id: 6,
      name: "GOR Ar-Rahmah",
      image: "sepak-bola.jpg",
      desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut rem aut in consectetur amet perferendis, quaerat labore voluptatem voluptas culpa, dolorem officiis, iusto temporibus vitae eos totam laboriosam velit necessitatibus.",
      price: 30000,
      location: "Jalan Bali",
      city: "Palembang",
      rating: "4.39",
   },
];
